version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-northeast-1:041967461206:task-definition/prodappstackprodFargateServiceTaskDefE883E3CC:3"
        LoadBalancerInfo:
          ContainerName: "my-app"
          ContainerPort: 8081